services:
  backend:
    container_name: backend
    image: alex.mazzoni3/flask_amusamentpark_app:1.0.0
    build: ./backend/
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - URL= http://localhost:4000
      - DB_URL=mysql+pymysql://root:admin@db/amusamentpark
    depends_on:
      - db
  
  db:
    container_name: db
    build: ./db/
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: amusamentpark
      MYSQL_ROOT_PASSWORD: admin